@echo off
echo Arrêt de tous les processus Node.js...
taskkill /f /im node.exe 2>nul
echo Nettoyage du cache...
rmdir /s /q node_modules\.cache 2>nul
rmdir /s /q build 2>nul
echo Installation des dépendances...
npm install
echo Démarrage de l'application...
npm start 